### ISSUE TITLE
ensemble problem

### ISSUE THREAD

**Issue by Emma-99** [lshiwjx/2s-AGCN#10]
您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！
![微信图片_20190727201517](https://user-images.githubusercontent.com/37145701/61994391-184be000-b0ac-11e9-9793-3f6e4d2232f0.png)

**Comment by lshiwjx** [comment]
提供信息太少了。不过融合代码其实挺简单的，我建议你看一下就应该能看出问题了 707687531 邮箱707687531@qq.com 签名由 网易邮箱大师 定制 On 07/27/2019 20:22, Emma-99 wrote: 您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Emma-99** [comment]
谢谢您的回复，我再好好看看代码，找找问题所在。
  

 

 ------------------ 原始邮件 ------------------
  发件人: "LShi"<notifications@github.com>;
 发送时间: 2019年7月28日(星期天) 凌晨0:57
 收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com>;
 抄送: "幻梦、"<1370516631@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [lshiwjx/2s-AGCN] ensemble problem (#10)

 

提供信息太少了。不过融合代码其实挺简单的，我建议你看一下就应该能看出问题了 707687531 邮箱707687531@qq.com 签名由 网易邮箱大师 定制 On 07/27/2019 20:22, Emma-99 wrote: 您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Emma-99** [comment]
我查看了融合代码，发现不是这里的问题。joint和bone测试得到的两个epoch1_test_score.pkl文件中，我发现样本的顺序是不同的，这导致融合的并不是同一个样本的score。想请教如何使测试时保存score文件中样本顺序是相同的？
![微信图片_20190728205410](https://user-images.githubusercontent.com/37145701/62007036-595ef580-b17b-11e9-9540-cc0983bbc7d9.png)

**Comment by lshiwjx** [comment]
测试时dataloader不要随机就好了: shuffle=False

**Comment by Emma-99** [comment]
非常感谢您的回复！我测试的时候设置了shuffle=False，得到的score文件顺序还是不一样，这点一直让我很困惑。我自己添加了几行代码来匹配两个score文件中的样本名称，得到了与您论文中相近的结果。

**Comment by Lyndsey-Xing** [comment]
> 非常感谢您的回复！我测试的时候设置了shuffle=False，得到的score文件顺序还是不一样，这点一直让我很困惑。我自己添加了几行代码来匹配两个score文件中的样本名称，得到了与您论文中相近的结果。

您好，我想请问你的pytorch版本使用0.3吗？您的cuda版本使用的是？我下载了pytorch0.3,cuda75，但我服务器是cuda80的，所以想请问一下您的配置～ 打扰了，谢谢

**Comment by Emma-99** [comment]
我用的是pytorch0.4，cuda9.1。------------------ 原始邮件 ------------------
发件人: "Lyndsey"<notifications@github.com>
发送时间: 2019年8月17日(星期六) 上午9:57
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com>;
抄送: "Emma-99"<1370516631@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lshiwjx/2s-AGCN] ensemble problem (#10)


 
非常感谢您的回复！我测试的时候设置了shuffle=False，得到的score文&#x4EF6;顺序还是不一样，这点一直让我很困惑。我自己添加了几行代码来匹配两个score文&#x4EF6;中的样本名称，得到了与您论文中相近的结果。
  
您好，我想请问你的pytorch版本使用0.3吗？您的cuda版本使用的是？我下载了pytorch0.3,cuda75，但我&#x670D;务器是cuda80的，所以想请问一下您的配置～ 打扰了，谢谢
 
&mdash;

**Comment by Anirudh257** [comment]
I have followed all the above tips but I am still unable to get the ensemble working properly. I made shuffle = False while testing on my best settings of joint and bone made the order of the data correct but I am still getting < 1 % accuracy while performing ensemble. @lshiwjx Please suggest something. My joint and bone accuracies are 81.28 and 80.43% respectively.

**Comment by wl-zhao** [comment]
The test result of each stream is saved as python dict, where the order of items will be ignored. To ensemble the streams correctly, you can do either of the following:
1. save the results as python list
2. in `ensemble.py`, traverse the results by the names of skeleton files (which are the keys of saved results)

**Comment by RayLeijingsi** [comment]
> 非常感谢您的回复！我测试的时候设置了shuffle=False，得到的score文件顺序还是不一样，这点一直让我很困惑。我自己添加了几行代码来匹配两个score文件中的样本名称，得到了与您论文中相近的结果。

您好，我也遇到了您说的问题，我用的是kinetics数据集。ensemble.py文件中获取score文件后都进行了排序，测试的shuffle=false。请问您是如何解决这个问题的？

**Comment by RayLeijingsi** [comment]
> > 非常感谢您的回复！我测试的时候设置了shuffle=False，得到的score文件顺序还是不一样，这点一直让我很困惑。我自己添加了几行代码来匹配两个score文件中的样本名称，得到了与您论文中相近的结果。
> 
> 您好，我也遇到了您说的问题，我用的是kinetics数据集。ensemble.py文件中获取score文件后都进行了排序，测试的shuffle=false。请问您是如何解决这个问题的？



> 非常感谢您的回复！我测试的时候设置了shuffle=False，得到的score文件顺序还是不一样，这点一直让我很困惑。我自己添加了几行代码来匹配两个score文件中的样本名称，得到了与您论文中相近的结果。

您好，我已经解决了融合精度较低的问题。由于score文件中是用字典存储的，所以它是乱序的。需要将ebsemble.py中label，r1，r2中的文件名进行排序，使其能够对应上。打扰您了。

**Comment by Anirudh257** [comment]
Thanks, @lshiwjx and @RayLeijingsi. Let me try reordering and calculate it again.

**Comment by LiJieqin** [comment]
>
你好，我想请教一下，我用的也是kinetics数据集，但是我在执行python main.py --config ./config/kinetics-skeleton/train_joint.yaml的时候,出现这种错误
/home/lijieqin/DGNN-PyTorch/model/agcn.py:59: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(self.PA, 1e-6)
/home/lijieqin/DGNN-PyTorch/model/agcn.py:27: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(conv.weight, mode='fan_out')
/home/lijieqin/DGNN-PyTorch/model/agcn.py:28: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(conv.bias, 0)
/home/lijieqin/DGNN-PyTorch/model/agcn.py:32: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(bn.weight, scale)
/home/lijieqin/DGNN-PyTorch/model/agcn.py:33: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(bn.bias, 0)
/home/lijieqin/DGNN-PyTorch/model/agcn.py:22: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  nn.init.normal(weight, 0, math.sqrt(2. / (n * k1 * k2 * branches)))
/home/lijieqin/DGNN-PyTorch/model/agcn.py:23: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(conv.bias, 0)
/home/lijieqin/DGNN-PyTorch/model/agcn.py:157: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  nn.init.normal(self.fc.weight, 0, math.sqrt(2. / num_class))
Traceback (most recent call last):
  File "/home/lijieqin/DGNN-PyTorch/main.py", line 605, in <module>
    processor = Processor(arg)
  File "/home/lijieqin/DGNN-PyTorch/main.py", line 200, in __init__
    self.load_data()
  File "/home/lijieqin/DGNN-PyTorch/main.py", line 210, in load_data
    dataset=Feeder(**self.arg.train_feeder_args),
TypeError: __init__() got an unexpected keyword argument 'data_path'
请问要怎么处理？或者能想你请教一下怎么在kinetics数据集上训练？

**Comment by LiJieqin** [comment]
> > 非常感谢您的回复！我测试的时候设置了shuffle=False，得到的score文件顺序还是不一样，这点一直让我很困惑。我自己添加了几行代码来匹配两个score文件中的样本名称，得到了与您论文中相近的结果。
> 
> 您好，我也遇到了您说的问题，我用的是kinetics数据集。ensemble.py文件中获取score文件后都进行了排序，测试的shuffle=false。请问您是如何解决这个问题的？
您好，我想请问个问题，为什么我在 用train_bone.yam训练的时候，得到的top1和top5很低，只有3%和8%？但是在用train_joint.yam训练的时候，得到的top1和top5跟论文是接近的。我用的是kinetics数据集

**Comment by czhaneva** [comment]
> 您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！
> ![微信图片_20190727201517](https://user-images.githubusercontent.com/37145701/61994391-184be000-b0ac-11e9-9793-3f6e4d2232f0.png)
我想请教下你有调整学习率或者改变其他参数么（随机种子、等等其他的），因为我始终达不到论文所述效果，所以有些困惑，非常期待你的回复，感谢！

**Comment by RayLeijingsi** [comment]
> > 您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！
> > ![微信图片_20190727201517](https://user-images.githubusercontent.com/37145701/61994391-184be000-b0ac-11e9-9793-3f6e4d2232f0.png)
> > 我想请教下你有调整学习率或者改变其他参数么（随机种子、等等其他的），因为我始终达不到论文所述效果，所以有些困惑，非常期待你的回复，感谢！

ensemble.py文件需要改动，建议你debug看一下label，r1, r2的内容，他们应该是对应的。请仔细参考楼主上面给出的解答，她还附了截图进行了标注。

**Comment by czhaneva** [comment]
> > > 您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！
> > > ![微信图片_20190727201517](https://user-images.githubusercontent.com/37145701/61994391-184be000-b0ac-11e9-9793-3f6e4d2232f0.png)
> > > 我想请教下你有调整学习率或者改变其他参数么（随机种子、等等其他的），因为我始终达不到论文所述效果，所以有些困惑，非常期待你的回复，感谢！
> 
> ensemble.py文件需要改动，建议你debug看一下label，r1, r2的内容，他们应该是对应的。请仔细参考楼主上面给出的解答，她还附了截图进行了标注。

我的ensemble已经可以正确运行，但是单个串流达不到93%以上的效果，所以想询问下是否需要调整其他哪些地方

**Comment by RayLeijingsi** [comment]
> > > > 您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！
> > > > ![微信图片_20190727201517](https://user-images.githubusercontent.com/37145701/61994391-184be000-b0ac-11e9-9793-3f6e4d2232f0.png)
> > > > 我想请教下你有调整学习率或者改变其他参数么（随机种子、等等其他的），因为我始终达不到论文所述效果，所以有些困惑，非常期待你的回复，感谢！
> > 
> > 
> > ensemble.py文件需要改动，建议你debug看一下label，r1, r2的内容，他们应该是对应的。请仔细参考楼主上面给出的解答，她还附了截图进行了标注。
> 
> 我的ensemble已经可以正确运行，但是单个串流达不到93%以上的效果，所以想询问下是否需要调整其他哪些地方

你的融合准确率是多少

**Comment by RayLeijingsi** [comment]
> > > > > 您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！
> > > > > ![微信图片_20190727201517](https://user-images.githubusercontent.com/37145701/61994391-184be000-b0ac-11e9-9793-3f6e4d2232f0.png)
> > > > > 我想请教下你有调整学习率或者改变其他参数么（随机种子、等等其他的），因为我始终达不到论文所述效果，所以有些困惑，非常期待你的回复，感谢！
> > > 
> > > 
> > > ensemble.py文件需要改动，建议你debug看一下label，r1, r2的内容，他们应该是对应的。请仔细参考楼主上面给出的解答，她还附了截图进行了标注。
> > 
> > 
> > 我的ensemble已经可以正确运行，但是单个串流达不到93%以上的效果，所以想询问下是否需要调整其他哪些地方
> 
> 你的融合准确率是多少

麻烦给出详细信息吧

**Comment by czhaneva** [comment]
> > > > > > 您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！
> > > > > > ![微信图片_20190727201517](https://user-images.githubusercontent.com/37145701/61994391-184be000-b0ac-11e9-9793-3f6e4d2232f0.png)
> > > > > > 我想请教下你有调整学习率或者改变其他参数么（随机种子、等等其他的），因为我始终达不到论文所述效果，所以有些困惑，非常期待你的回复，感谢！
> > > > 
> > > > 
> > > > ensemble.py文件需要改动，建议你debug看一下label，r1, r2的内容，他们应该是对应的。请仔细参考楼主上面给出的解答，她还附了截图进行了标注。
> > > 
> > > 
> > > 我的ensemble已经可以正确运行，但是单个串流达不到93%以上的效果，所以想询问下是否需要调整其他哪些地方
> > 
> > 
> > 你的融合准确率是多少
> 
> 麻烦给出详细信息吧

CV joint/bone 都只有92.8%的左右的准确率， Emsemble后的结果为94.3%，所有参数均未改动。

**Comment by RayLeijingsi** [comment]
> > > > > > > 您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！
> > > > > > > ![微信图片_20190727201517](https://user-images.githubusercontent.com/37145701/61994391-184be000-b0ac-11e9-9793-3f6e4d2232f0.png)
> > > > > > > 我想请教下你有调整学习率或者改变其他参数么（随机种子、等等其他的），因为我始终达不到论文所述效果，所以有些困惑，非常期待你的回复，感谢！
> > > > > 
> > > > > 
> > > > > ensemble.py文件需要改动，建议你debug看一下label，r1, r2的内容，他们应该是对应的。请仔细参考楼主上面给出的解答，她还附了截图进行了标注。
> > > > 
> > > > 
> > > > 我的ensemble已经可以正确运行，但是单个串流达不到93%以上的效果，所以想询问下是否需要调整其他哪些地方
> > > 
> > > 
> > > 你的融合准确率是多少
> > 
> > 
> > 麻烦给出详细信息吧
> 
> CV joint/bone 都只有92.8%的左右的准确率， Emsemble后的结果为94.3%，所有参数均未改动。

1%的差距，正常范围吧，我复现出来比论文里高一点呢。

**Comment by czhaneva** [comment]
> > > > > 您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！
> > > > > ![微信图片_20190727201517](https://user-images.githubusercontent.com/37145701/61994391-184be000-b0ac-11e9-9793-3f6e4d2232f0.png)
> > > > > 我想请教下你有调整学习率或者改变其他参数么（随机种子、等等其他的），因为我始终达不到论文所述效果，所以有些困惑，非常期待你的回复，感谢！
> > > 
> > > 
> > > ensemble.py文件需要改动，建议你debug看一下label，r1, r2的内容，他们应该是对应的。请仔细参考楼主上面给出的解答，她还附了截图进行了标注。
> > 
> > 
> > 我的ensemble已经可以正确运行，但是单个串流达不到93%以上的效果，所以想询问下是否需要调整其他哪些地方
> 
> 你的融合准确率是多少

好的，感谢啦，我只是在想是不是哪个地方参数的问题，毕竟现在已经这么高了，一个点的提升已经很不容易啦。多谢啦！

**Comment by LiJieqin** [comment]
您好，我想请教一下为什么我用kinetics数据集的时候，在joint上有35.3%，但是在bone上训练只有8%的准确率，融合之后为29.7%，不知道是哪里出了问题。希望能得到您的回复，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Roy790422795"<notifications@github.com&gt;; 
发送时间: 2019年11月21日(星期四) 上午10:51
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "李洁沁"<980595252@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] ensemble problem (#10)



     
您好，我想请教一下为什么我融合的结果完全不对，在joint和bone上分别训练都有93%以上的准确率，融合之后结果1.7%，ensemble.py文件没有改动，不知道是哪里出了问题。希望能得到您的回复，非常感谢！
 
 我想请教下你有调整学习率或者改变其他参数么（随机种子、等等其他的），因为我始终达不到论文所述效果，所以有些困惑，非常期待你的回复，感谢！
   
ensemble.py文件需要改动，建议你debug看一下label，r1, r2的内容，他们应该是对应的。请仔细参考楼主上面给出的解答，她还附了截图进行了标注。
  
我的ensemble已经可以正确运行，但是单个串流达不到93%以上的效果，所以想询问下是否需要调整其他哪些地方
  
你的融合准确率是多少
  
好的，感谢啦，我只是在想是不是哪个地方参数的问题，毕竟现在已经这么高了，一个点的提升已经很不容易啦。多谢啦！

**Comment by dangao250** [comment]
> 我用的是pytorch0.4，cuda9.1。------------------ 原始邮件 ------------------ 发件人: "Lyndsey"<notifications@github.com> 发送时间: 2019年8月17日(星期六) 上午9:57 收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com>; 抄送: "Emma-99"<1370516631@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [lshiwjx/2s-AGCN] ensemble problem (#10) 非常感谢您的回复！我测试的时候设置了shuffle=False，得到的score文&#x4EF6;顺序还是不一样，这点一直让我很困惑。我自己添加了几行代码来匹配两个score文&#x4EF6;中的样本名称，得到了与您论文中相近的结果。 您好，我想请问你的pytorch版本使用0.3吗？您的cuda版本使用的是？我下载了pytorch0.3,cuda75，但我&#x670D;务器是cuda80的，所以想请问一下您的配置～ 打扰了，谢谢 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
---------------------------------------
请问你可以告诉我你添加的代码达到论文的水平吗  我的也特别低 然后问一下alpha这个值怎么求的是多少

**Comment by dangao250** [comment]
> 非常感谢您的回复！我测试的时候设置了shuffle=False，得到的score文件顺序还是不一样，这点一直让我很困惑。我自己添加了几行代码来匹配两个score文件中的样本名称，得到了与您论文中相近的结果。

就是你添加了什么代码可以分享一下吗  还有alpha值是多少 怎么算的

**Comment by dangao250** [comment]
> I have followed all the above tips but I am still unable to get the ensemble working properly. I made shuffle = False while testing on my best settings of joint and bone made the order of the data correct but I am still getting < 1 % accuracy while performing ensemble. @lshiwjx Please suggest something. My joint and bone accuracies are 81.28 and 80.43% respectively.
Can you show me the fusion code, still don't understand this operation

**Comment by dangao250** [comment]
> Thanks, @lshiwjx and @RayLeijingsi. Let me try reordering and calculate it again.

Can you show me the fusion code, still don't understand this operation

**Comment by Just-A-Peek** [comment]
> > I have followed all the above tips but I am still unable to get the ensemble working properly. I made shuffle = False while testing on my best settings of joint and bone made the order of the data correct but I am still getting < 1 % accuracy while performing ensemble. @lshiwjx Please suggest something. My joint and bone accuracies are 81.28 and 80.43% respectively.
> > Can you show me the fusion code, still don't understand this operation

Are you sure make the data have a correct order?

**Comment by kunruya** [comment]
I add these codes before the loop and it works.
`r1.sort(key=lambda k:k[0])`
`r2.sort(key=lambda k:k[0])`
`label=label.T[np.lexsort(label[::-1,:])].T`
