### ISSUE TITLE
ValueError: invalid literal for int() with base 10: './pre_train/ki_agcn'

### ISSUE THREAD

**Issue by dongle329** [lshiwjx/2s-AGCN#57]
hello
when i run python main.py --config ./config/kinetics-skeleton/test_joint.yaml   have this problem 
Traceback (most recent call last):
  File "main.py", line 577, in <module>
    processor = Processor(arg)
  File "main.py", line 213, in __init__
    self.load_model()
  File "main.py", line 249, in load_model
    self.global_step = int(arg.weights[:-3].split('-')[-1])
ValueError: invalid literal for int() with base 10: './pre_train/ki_agcn

thank you

**Comment by YanjunChen** [comment]
> hello
> when i run python main.py --config ./config/kinetics-skeleton/test_joint.yaml have this problem
> Traceback (most recent call last):
> File "main.py", line 577, in
> processor = Processor(arg)
> File "main.py", line 213, in **init**
> self.load_model()
> File "main.py", line 249, in load_model
> self.global_step = int(arg.weights[:-3].split('-')[-1])
> ValueError: invalid literal for int() with base 10: './pre_train/ki_agcn
> 
> thank you

same problem occured

**Comment by erinchen824** [comment]
you can set line 249 as 
self.global_step = 0
since initial command is to load the epoch number of the model when it has one.

**Comment by YuQi9797** [comment]
同样的问题，请问如何解决？  仅仅是将`self.global_step = 0 ` 吗?   同时模型训练完毕后，并无`./pre_train/pd_agcn.pt` 该路径以及文件。

**Comment by doMoreCode** [comment]
> 同样的问题，请问如何解决？ 仅仅是将`self.global_step = 0 ` 吗? 同时模型训练完毕后，并无`./pre_train/pd_agcn.pt` 该路径以及文件。

去test的yaml文件里面将对应的预训练模型位置改成你训练得到的pt文件就可以了，他这个和mmskeleton的测试流程差不多。

**Comment by doMoreCode** [comment]
> hello
> when i run python main.py --config ./config/kinetics-skeleton/test_joint.yaml have this problem
> Traceback (most recent call last):
> File "main.py", line 577, in
> processor = Processor(arg)
> File "main.py", line 213, in **init**
> self.load_model()
> File "main.py", line 249, in load_model
> self.global_step = int(arg.weights[:-3].split('-')[-1])
> ValueError: invalid literal for int() with base 10: './pre_train/ki_agcn
> 
> thank you

maybe check your pt path in test yaml,  i got the result after this.

**Comment by YuQi9797** [comment]
好的，俺去试试！ 感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lshiwjx/2s-AGCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月13日(星期五) 下午5:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lshiwjx/2s-AGCN] ValueError: invalid literal for int() with base 10: './pre_train/ki_agcn' (#57)





  
hello
 when i run python main.py --config ./config/kinetics-skeleton/test_joint.yaml have this problem
 Traceback (most recent call last):
 File "main.py", line 577, in
 processor = Processor(arg)
 File "main.py", line 213, in init
 self.load_model()
 File "main.py", line 249, in load_model
 self.global_step = int(arg.weights[:-3].split('-')[-1])
 ValueError: invalid literal for int() with base 10: './pre_train/ki_agcn
 
thank you
  
maybe check your pt path in test yaml,  i got the result after this.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
