### ISSUE TITLE
some kind of device error

### ISSUE THREAD

**Issue by alirazaee** [lshiwjx/2s-AGCN#66]
Traceback (most recent call last):
  File "/media/ali/hdd6/Onedrive data/PycharmProjects/activity_rec1/2s-AGCN-master/main.py", line 577, in <module>
    processor = Processor(arg)
  File "/media/ali/hdd6/Onedrive data/PycharmProjects/activity_rec1/2s-AGCN-master/main.py", line 213, in __init__
    self.load_model()
  File "/media/ali/hdd6/Onedrive data/PycharmProjects/activity_rec1/2s-AGCN-master/main.py", line 286, in load_model
    output_device=output_device)
  File "/home/ali/anaconda3/envs/activity_rec/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 136, in __init__
    _check_balance(self.device_ids)
  File "/home/ali/anaconda3/envs/activity_rec/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 19, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/ali/anaconda3/envs/activity_rec/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 19, in <listcomp>
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/ali/anaconda3/envs/activity_rec/lib/python3.7/site-packages/torch/cuda/__init__.py", line 317, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

Process finished with exit code 1

**Comment by Ida-Ida** [comment]
In case you couldn't solve it yet: 
You may need to edit the `device` property in the config files, so that it matches your used GPU(s).

**Comment by liqier** [comment]
How to edit the device?

**Comment by Ida-Ida** [comment]
Inside your `config/ntu.../..yaml` file, you can specify different parameters. Among them, `device:`. 
E.g. if you have only one available GPU, set the device parameter to the index 0.  Probably you need to reduce the `batch size` parameter there as well. If it‘s too high, you‘ll get a CUDA out of memory error.

Pls note: you may need to learn more about how pytorch / CUDA and the config works in general, especially if you run in further issues.

**Comment by liqier** [comment]
Thank you very much.
