### ISSUE TITLE
No directory found ./pre_train/ki_agcn.pt

### ISSUE THREAD

**Issue by joshivaibhav** [lshiwjx/2s-AGCN#70]
I am trying to test using the Kinetics dataset and I am getting this error : 

`
Traceback (most recent call last):
  File "main.py", line 582, in <module>
    processor = Processor(arg)
  File "main.py", line 213, in __init__
    self.load_model()
  File "main.py", line 256, in load_model
    weights = torch.load(self.arg.weights)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './pre_train/ki_agcn.pt'
`

**Comment by joshivaibhav** [comment]
This concerns the weights entry in the config file. Is there any other value I can specify? Do I have to use these weight values?

**Comment by Xuanoh** [comment]
> This concerns the weights entry in the config file. Is there any other value I can specify? Do I have to use these weight values?

has this problem been solved

**Comment by ruthless-man** [comment]
> This concerns the weights entry in the config file. Is there any other value I can specify? Do I have to use these weight values?

You can modify the parameters in the config file using the model you train in the runs folder
